version: v1.3.0

dsn: postgres://kratos:kratos_secret@postgres-kratos:5432/kratos?sslmode=disable

serve:
  public:
    base_url: http://localhost:4433/
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:8080
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      allowed_headers:
        - Authorization
        - Content-Type
        - Cookie
      exposed_headers:
        - Content-Type
        - Set-Cookie
      allow_credentials: true
    host: 0.0.0.0
    port: 4433
  admin:
    base_url: http://localhost:4434/
    host: 0.0.0.0
    port: 4434

session:
  cookie:
    domain: localhost
    path: /
    same_site: Lax
    persistent: true
  lifespan: 24h
  earliest_possible_extend: 1h
  whoami:
    required_aal: aal1

selfservice:
  default_browser_return_url: http://localhost:8080/
  allowed_return_urls:
    - http://localhost:8080

  methods:
    password:
      enabled: true
      config:
        haveibeenpwned_enabled: false
    totp:
      config:
        issuer: MyApp
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true

  flows:
    error:
      ui_url: http://localhost:8080/error

    settings:
      ui_url: http://localhost:8080/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: false
      ui_url: http://localhost:8080/recovery
      use: link

    verification:
      enabled: false
      ui_url: http://localhost:8080/verification
      use: link
      after:
        default_browser_return_url: http://localhost:8080/

    logout:
      after:
        default_browser_return_url: http://localhost:8080/login

    login:
      ui_url: http://localhost:8080/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://localhost:8080/registration
      after:
        password:
          hooks:
            - hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - A1B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6
  cipher:
    - Z9Y8X7W6V5U4T3S2R1Q0P9O8N7M6L5K4

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  delivery_strategy: http
  http:
    request_config:
      url: http://localhost:8080/email
      method: POST
      body: file:///etc/config/kratos/.mail.api.request.jsonnet
      headers:
        Content-Type: application/json
