serve:
  public:
    port: 4444
    host: 0.0.0.0
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:8080
        - http://localhost:8081
      allowed_methods:
        - GET
        - POST
      allowed_headers:
        - Authorization
        - Content-Type
        - Cookie
      exposed_headers:
        - Content-Type
      allow_credentials: true
  admin:
    port: 4445
    host: 0.0.0.0
dsn: postgres://hydra:secret@postgres-hydra:5432/hydra?sslmode=disable
urls:
  self:
    issuer: http://localhost:4444
  login: http://localhost:3000/login
  consent: http://localhost:3000/consent
  logout: http://localhost:3000/logout
  error: http://localhost:3000/error
secrets:
  system:
    - youReallyNeedToChangeThis32CharSecret
oidc:
  subject_identifiers:
    supported_types:
      - public
      - pairwise
    pairwise:
      salt: youReallyNeedToChangeThisSalt
oauth2:
  pkce:
    enforced: false
log:
  level: debug
  format: json
  leak_sensitive_values: true
